### PR TITLE
Updated scale dialog so slider snaps to steps

### PR DESCRIPTION
**Pull request by PatrickGMM**
Updated scale dialog so moving the slider with the mouse will snap to the closest step instead of allowing any arbitrary value to be selected

### CODE REVIEW

**Comment by v1cont** [comment]
can you make this feature optional?

**Comment by PatrickGMM** [comment]
I can do that. Do you have a preference for the command line option name.

**Comment by v1cont** [comment]
the name must be unique single word

**Comment by v1cont** [comment]
merged, thank you

**Pull request merged**
