### PR TITLE
fix null pointer to form button command output

### PR DESCRIPTION
**Pull request by step-**
related to #214

### CODE REVIEW

**Comment by step-** [comment]
Script to demonstrate SIGSEGV exception. Click button 1 then immediately after click button 2. Wait for sleep to complete and....

```
(yad:8940): GLib-CRITICAL **: 11:15:21.238: g_strsplit: assertion 'string != NULL' failed
./test.sh: line 27:  8940 Segmentation fault      yad --center --use-interp='bash -xc "%s"' --form --field="[1] can disable #1:fbtn" "@candisable" --field="[2] can enable  #1:fbtn" "@canenable " --button=quit:0 --buttons-layout=center
```

test.sh
```sh
#!/bin/bash -a

# disable #1 and stay disabled
candisable () {
: "1>"
	echo "1:@disabled@"
	sleep 2 # SIGSEGV w/o PR #217
: "<1"
}

# enable #1
canenable  () {
: "2>"
	echo "1:@candisable"
	sleep 5 # SIGSEGV w/o PR #217
: "<2"
}

yad \
	--center --use-interp='bash -xc "%s"' --form \
	--field="[1] can disable #1:fbtn" "@candisable" \
	--field="[2] can enable  #1:fbtn" "@canenable " \
	--button=quit:0 --buttons-layout=center
```

**Comment by v1cont** [comment]
cannot reproduce SIGSEGV. what version of glib you are using?

**Comment by step-** [comment]
2.58.1

**Comment by v1cont** [comment]
made it some other way, please check latest git

**Comment by step-** [comment]
OK, can't reproduce anymore.

**Pull request closed without merging**
